.github/workflows/semver_tag_action.yml
Using https://github.com/marketplace/actions/semver-release
=> Automatically create semver tag based on PR label

.github/pull_request_template.md
Using a pull request template to do this:
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
=> Add checkbox for semver label on all pull requests

action.yml
=> Update name, author and description

magefile.go, magefile_test.go
Also display error output when running tests.
Fixes #21
=> Log entry info message to stdout not stderr

action.yml
=> Fix unexpected input warning about GitHub token

.github/workflows/test.yml
=> Run tests on every push

internal/github/pullrequest/action.go, internal/github/pullrequest/label_checker.go, internal/github/pullrequest/pull_request.go, internal/util/error.go, internal/util/strings.go
=> Extract method to util package

.github/workflows/check_semver_labels.yml, action.yml, internal/github/action.go, label_checker_test.go
=> Rename input variable

action.yml, internal/github/action.go, internal/github/pullrequest/labels.go, label_checker_test.go
=> Add check which ensures none of specified labels are present

action.yml, internal/github/action.go, internal/github/pullrequest/labels.go, label_checker_test.go
=> Add check for any of specified labels

internal/github/action.go, label_checker.go
=> Improve readability - minor refactor

internal/github/action.go
=> Extract method refactor

entrypoint.sh
This should have been removed some time ago - it's not used anywhere.
=> Remove obsolete entrypoint.sh

action.yml, internal/github/action.go, label_checker_test.go
=> Use comma-lists for the label inputs

README.md
https://goreportcard.com/report/github.com/agilepathway/label-checker
=> Add Go Report status badge to README

README.md
=> Add Docker status badges

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .vscode/settings.json
Benefits of [Codespaces](https://docs.github.com/en/github/developing-online-with-codespaces/about-codespaces):
- All configuration is in source code and ready to be used - no set up needed
- No need for any software to be installed and maintained locally
- Can develop on any machine (including an iPad) - all that’s needed is a browser
=> Enable development in Codespaces

action.yml
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
=> Add GitHub Action branding

.github/workflows/build_and_push_image.yml, .github/workflows/check-commit-message.yml, .github/workflows/check_semver_labels.yml, .github/workflows/github_tag_and_release.yml, .github/workflows/integration_test.yml, .github/workflows/reviewdog.yml, .github/workflows/virtual_test.yml
We want to pin all our dependencies, so that our builds are
reproducible.
=> Use fixed version of ubuntu

CONTRIBUTING.md, README.md, internal/github/action.go, internal/github/pullrequest/pull_request.go, label_checker.go, label_checker_test.go, testdata/github_enterprise_server_api.json
Github enterprise just needs a different endpoint to make this work.  
Luckily its provided by github's env vars
=> Add github enterprise support

README.md
The previous commit was pushed directly to the `master` branch by mistake, meaning that a release was not created.  The whitespace change is simply to trigger a PR, meaning that a new release will be created.
=> Add whitespace to enable a release

.devcontainer/devcontainer.json
Having the [GitHub Actions VS Code extension][1] installed makes editing GitHub Actions workflow files safer and easier.
[1]: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions
=> Add GitHub Actions VS Code devcontainer extension

README.md, SECURITY.md
=> Document security vulnerability reporting process
