- .github/workflows/reviewdog.yml
NB when we add golangci-lint linting for go then we will probably
include misspell checking there too.  We also want misspell to check
markdown files too though, so we'll still need this separate check as
well.
There will be no harm in having any go file spelling errors being
reported twice.
> Add misspell check via reviewdog

- .github/workflows/reviewdog.yml
https://github.com/reviewdog/action-languagetool
https://languagetool.org/
https://github.com/languagetool-org/languagetool
Use en locale for languagetool checks
Use `en` as it does not do spell checking, whereas if we use `en-gb`
`en-gb` then it flags errors for the US spelling of `LICENSE`
(which is what it should do).
As LICENSE is the conventional name for the licence file, we
don't want it to be reported.
Our spell checking is done by misspell (which we have set to allow UK
or US variants e.g. colour and color), so we don't want languagetool
to do spell checking anyway.
> Add languagetool check via reviewdog

- action.yml
- go.mod
- go.sum
- internal/github/labels.go
- magefile_test.go
Fixes a bug whereby a PR could show that the check has passed, but
still not allow the pull request to be merged.  This is because GitHub
Actions create a separate new instance of the check for some different
event types, e.g. the `labeled` event creates a new check instance
separate from the `push` event checks.  So if, for instance, a consumer:
1. pushed a commit when there is no required label
2. added the required label
then the `lableled` instance of the check would pass, but the push would
still show the initial failure.
The fix in this commit is to retrieve the GitHub
labels for the pull request via the GitHub API, instead of using the
labels in the GitHub Action's event JSON (which is a frozen snapshot of
the labels at the time of committing and therefore does not stay up to
date …
> Fix bug where consumers were unable to merge PRs

- .github/workflows/test.yml
They were taking too long on Windows or MacOS.
> Only run tests on Linux, not Windows or MacOS

- .github/pull_request_template.md
It is no longer needed as the label checker will ensure that we cannot
process a pull request unless there is a semantic version label.
> Remove obsolete pull request template

- .github/workflows/check_semver_labels.yml
- .github/workflows/test.yml
- action.yml
- internal/github/action.go
- label_checker_test.go
Removed the unnecessary manual translation of the input variables into
environment variables, in the action.yml.  It is not needed because
GitHub actions automatically create environment variables for the input
variables.[1]
NB The manual translation would not work when we move to a minimal
pre-built Docker image (#22).
Also renamed the inputs to have underscores instead of dashes, as
dashes are not valid POSIX standard names.[2]
(This caused a problem as I could not set these environment variables
when running the tests, causing the tests to fail.)
(I fed back to GitHub (via their feedback form [3]) that they may want
to convert dashes to underscores when converting the input variables to
environment variables.)
[1] https://help.github.com/en/actions/creating-actions/metadata-syntax-for-g …
> Tidy the input variables

- .github/workflows/build_and_push_image.yml
Run the Docker build and push on "create" as well as "push", so that it
is triggered when the tag is created (by the semver-release-action).
> Fix Docker semantic version tagging

- .github/workflows/build_and_push_image.yml
- .github/workflows/github_tag_and_release.yml
Fix is to do a Docker build and push within the same GitHub Action that
creates the new tag.
> Fix semantic version tagging in Docker

- Dockerfile
This commit removes the DWARF debugging information[1], resulting in the
Docker image size shrinking from 4.76MB to 2.88MB.
Decided not to try to also turn off generation of the Go symbol table
using the `-s` flag, as:
1. the GOFLAGS functionality currently only allows 1 ldflag to be set[2]
(NB this may be fixed in Go 1.15[3])
2. The improvements to the binary size in Go 1.15 [4] mean that the `-s`
flag will no longer really do anything[5]
Will also try shrinking the binary size further using upx[6] in a
separate pull request.
[1] https://stackoverflow.com/a/22276273
[2] https://github.com/golang/go/issues/38522
[3] https://github.com/golang/go/issues/26849#issuecomment-615953358
[4] See #64
[5] https://twitter.com/bradfitz/status/1256989624590712834
[6] https://upx.github.io/
> Speed up label checking by making binary smaller

- Dockerfile
This shrinks the binary size from 2.88MB to 2.7MB (not a huge drop, but
still worth doing nonetheless).
UPX: https://upx.github.io/
As per this example from Seth Vargo[1]
Filippo Valsorda also has a good explanation of this technique[2]
[1] https://www.sethvargo.com/writing-github-actions-in-go/
[2] https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/
> Speed up label checking using UPX to shrink binary

- Dockerfile
This reduces the binary size from 2.7MB to 2.57MB (not a huge drop, but
worth doing nonetheless)
Using the strip command as per this example:
https://www.sethvargo.com/writing-github-actions-in-go/
This post[1] suggests that the Go team do not recommend doing this, as
it may break the executable.  Still going ahead though, we can always
revert this change if we encounter any problems.
[1] https://stackoverflow.com/questions/30005878/avoid-debugging-information-on-golang#comment48168448_30007760
> Speed up label checking by stripping symbols

- .github/workflows/check_semver_labels.yml
The repo uses the label checker to validate its own pull requests, so
this commit updates that check to use the new comma-separated label
inputs.
> Use the new comma-separated label inputs

- .github/workflows/test.yml
- README.md
Also renamed the corresponding workflow, as "Tests passing"
reads better on the badge than "Test passing".
> Add tests status badge to README

- .devcontainer/Dockerfile
- .github/CODEOWNERS
- .github/workflows/integration_test.yml
- .github/workflows/virtual_test.yml
- .vscode/settings.json
- .yamllint.yml
- CONTRIBUTING.md
- README.md
- label_checker_test.go
- testdata/github_api.json
> Enable tests to run without a GitHub personal access token

- .vscode/settings.json
All this flag does is to add `-S` when calling git commit[1].  The steps
carried out to get the vscode terminal working with a gpg passphrase
both locally and in a remote container are documented in #91
[1] https://github.com/microsoft/vscode/issues/97300#issuecomment-626647293
> Enable vscode commit signing flag

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Zsh is the default shell on MacOS from Catalina onwards[1], so it makes
sense to use it as the default on VS Code too.
[1] https://support.apple.com/en-us/HT208050
> Use Zsh as the default terminal shell in VS Code

- .github/workflows/check-commit-message.yml
Using a third party GitHub Action[1], which checks commit messages
based on the guidelines set out by Chris Beams[2]
[1] https://github.com/mristin/opinionated-commit-message
[2] https://chris.beams.io/posts/git-commit/
Closes #88
> Check commit messages for correctness

- .github/workflows/github_tag_and_release.yml
Prior to this commit, when creating a new release (automatically upon a
pull request merge), the release would be populated with the entire
commit history instead of just the commits pertaining to the change.
This fix updates to the latest major version v2 of goreleaser.
> Fix releases changelog issue

- .github/workflows/check-commit-message.yml
Prior to this fix, one line git commit messages would be rejected by the
check.
Fix is to update to the latest version of the checker, which has the fix
for this[1]
Also see this discussion [2]
[1] https://github.com/mristin/opinionated-commit-message#one-liners
[2] https://github.com/mristin/opinionated-commit-message/issues/55
> Accept one line git commit messages

- .github/workflows/virtual_test.yml
This means that we no longer have to install Hoverfly manually within
our own code here.
Using this action:
https://github.com/agilepathway/hoverfly-github-action
> Use separate GitHub Action to install Hoverfly

- .github/workflows/virtual_test.yml
We now invoke a script in the Hoverfly GitHub Action[1] to install and
trust the Hoverfly default cert.  This simplifies our code as the logic
has moved to the Hoverfly action.
[1] https://github.com/agilepathway/hoverfly-github-action
> Use Hoverfly action to enable https simulations

- .github/workflows/check-commit-message.yml
Updated to the latest version of the commit message checker which
contains [this new feature][1]
[1]: mristin/opinionated-commit-message#59
> Allow long URLs in commit messages

- .github/workflows/check-commit-message.yml
There is no need to run the commit message checks on master, because
the master branch is protected.  We continue to run the commit message
checks on all feature branches.
> Stop commit message style checks on master

- .github/workflows/integration_test.yml
- .github/workflows/virtual_test.yml
This is to ensure that we continue to have confidence that the
functionality works, and so that we are alerted to any regressions.
Using the [GitHub Actions scheduler functionality][1]
Closes #33
[1]: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
> Run the tests nightly

- .github/workflows/check-commit-message.yml
Had inadvertently excluded `main` instead of `master`, in #102.
> Fix commit message check master branch exclusion

- .github/DEPENDENCIES.md
- .github/dependabot.yml
- .github/workflows/build_and_push_image.yml
- .github/workflows/check_semver_labels.yml
- .github/workflows/github_tag_and_release.yml
- .github/workflows/integration_test.yml
- .github/workflows/reviewdog.yml
- .github/workflows/virtual_test.yml
- CONTRIBUTING.md
- README.md
Use pinned versions in GitHub Actions we consume, tohelp ensure that our
builds are idempotent and reproducible.
Using [Dependabot][1] to keep these pinned versions up to date.
[1]: https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot
> Update GitHub Actions dependencies automatically

- README.md
It makes sense to make the "why" more prominent, so that people see why
this label checker is a good one for them to use.
> Promote the why to the top of the README

- .github/DEPENDENCIES.md
- .github/workflows/check-commit-message.yml
- .github/workflows/dependabot_hack.yml
This is a hack, to get Dependabot to notify us about version updates for
dependencies that it cannot update automatically.
We never want this hack GitHub Action to be triggered (because the
Dependabot doesn't need the action to be triggered in order to carry out
it's version updating), so we have set it to only ever trigger on a
branch name which we will never have.
The PR that Dependabot creates will only have the update for this
`dependabot_hack` file, so we'll have to then manually update the
version wherever it is specified too.  We should do this in the same
PR that Dependabot has created.
[1]: https://dependabot.com/github-actions/
[2]: https://github.com/agilepathway/label-checker
> Notify us of non-automatic version updates

- .github/workflows/check-commit-message.yml
Commits which are automatically generated by Dependabot typically have
a body line length of [more than the 72 character limit][1] which our
check requires.
[1]: https://github.com/dependabot/feedback/issues/165#issuecomment-544498501
> Exclude Dependabot commits from message checks

- .devcontainer/Dockerfile
- .github/workflows/dependabot_hack.yml
This is to help ensure that our builds are reproducible.
Also set the dependencies to trigger a PR via Dependabot, which will be
our cue to manually update the Dockerfile with the new version.
> Pin Go dependencies in devcontainer Dockerfile

- .devcontainer/Dockerfile
- .github/DEPENDENCIES.md
- .github/ISSUE_TEMPLATE/scheduled/update-dockerfile-dependencies.md
- .github/workflows/dependabot_hack.yml
- .github/workflows/schedule_dockerfile_dependency_updates_issue.yml
We want to pin all versions in our codebase, so that our builds are
reproducible.
We have to update the Dockerfile dependencies manually at the moment,
so this commit also schedules an issue to be created every 6 months to
prompt us to do so.
> Pin Dockerfile apt-get dependencies

- .devcontainer/Dockerfile
Now that we are pinning all the dependencies in our devcontainer
Dockerfile, we don't need to suppress Hadolint enforcing pinned versions
anymore.
> Reinstate Hadolint pinned versions check

- .github/workflows/dependabot_hack.yml
- Dockerfile
We want to pin all of our versions in our codebase as specifically as we
can, to make our builds reproducible.
Also documented that the version should be updated when we update our Go
version across the board.
> Pin base image in Dockerfile more specifically

- Dockerfile
We want all of our dependencies to be pinned, so that we have
reproducible builds.
Closes #68
> Pin UPX version in Dockerfile

- internal/github/action.go
- label_checker_test.go
This is an important bug fix, as prior to this commit all four label
checks (`one_of`, `none_of`, `all_of`, `any_of`) were always running,
even when not all of the checks were specified to run in the user's
GitHub Actions yaml file.  This in turn was causing unexpected results
when running the Action, e.g. it could cause the pull request validation
to fail when it should pass, and vice versa.
The bug was caused by the code expecting the check values by default
not to be set at all, whereas in reality they default to an empty
string.
> Fix bug which caused all checks to always run

- .github/workflows/reviewdog.yml
- .github/workflows/virtual_test.yml
Prior to this commit the [status checks][1] that we need to run on pull
requests were only set to run on pushes.  This meant that they were not
being run when a contributor submitted a PR from a fork.  To fix this
we now run the required status check workflows explicitly on pull
requests as well as pushes.
[1]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks
> Enable required status checks on forked PRs

- .github/workflows/github_tag_and_release.yml
The [issue][1] was that a new release was not being created properly
when the PR came from a fork.
The fix is to trigger the release process on [`pull_request_target`][2]
rather than `pull_request`.  There are some [security concerns][3] to be
aware of when using `pull_request_target`, but they are not applicable
to our use case here, as we only trigger it when the PR is closed (which
means no danger that a malicious actor could run malicious code without
it having been reviewed).
[1]: https://github.com/agilepathway/label-checker/runs/5633353335?check_suite_focus=true
[2]: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
[3]: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
> Fix releases for PRs from forks

- .devcontainer/Dockerfile
The problem was caused by using an out of date version of Hoverfly which
had an out date certificate (we use Hoverfly for mocking calls to the
Gitlab API when running thetests).  Fixed by bumping the Hoverfly
version.
> Fix problem when running tests locally

- .devcontainer/devcontainer.json
The remote container dev environment was configured to use zsh, which
there was a problem with.  This commit removes zsh as the remote
container terminal so that the default bash terminal is used instead.
> Fix dev environment terminal problem

- .github/workflows/build_and_push_image.yml
The build on forks was failing because the GitHub Action which tests the
building and pushing the of the Docker image requires access to GitHub
Actions secrets, and forks rightly don't have access to them.  So this
commit [excludes forks from running this GitHub Action][1] (they don't
need to run it, as the additional confidence from it is just a nice to
have).
This ideally would have been part of #274, but was missed.
[1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
> Fix build on forks

- .github/workflows/integration_test.yml
The build on forks was failing because the GitHub Action which runs the
integration tests requires a GitHub token with access to an agilepathway
repo, and forks rightly don't have access.  So this commit [excludes
forks from running this GitHub Action][1] (they don't need to run it,
as the additional confidence from it is just a nice to have, as we also
have the tests which run using mocks and which do run fine on forks).
[1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
> Skip integration tests on forks

- .golangci.yml
Prior to this commit, running the linters resulted in:
```
WARN [runner] 
The linter 'golint' is deprecated (since v1.41.0) due to: 
The repository of the linter has been archived by the owner.  
Replaced by revive.
WARN [runner]
The linter 'interfacer' is deprecated (since v1.38.0) due to:
The repository of the linter has been archived by the owner.  
WARN [runner] 
The linter 'maligned' is deprecated (since v1.38.0) due to:
The repository of the linter has been archived by the owner.  
Replaced by govet 'fieldalignment'. 
WARN [runner] 
The linter 'scopelint' is deprecated (since v1.39.0) due to:
The repository of the linter has been deprecated by the owner. 
Replaced by exportloopref. 
```
To remedy this I have:
* Removed `interfacer` because it has been
* [determined to be unreliable …
> Update and Remove old/deprecated linters

- .github/workflows/integration_test.yml
- .github/workflows/virtual_test.yml
The only reason that the tests were not added as part of the previous
commit (which enabled GitHub Enterprise) was that the previous commit
was a contribution from a fork, and it was not possible for me to amend
the GitHub Actions workflow files on a fork (rightly, for security
reasons).
NB We do not run the integration tests in GitHub Enterprise Server mode
as that would require having a real GitHub Enterprise Server, which
would be expensive in time and money to maintain.  But having them run
as integration tests in GitHub Enterprise Cloud mode gives us pretty
good test coverage.
> Add GitHub Enterprise tests to CI/CD pipelines

- action.yml
When we added support for GitHub Enterprise in the two commits
immediately preceding this one, we forgot to specify the new [GitHub
Actions input parameter][1] in the `action.yml`.  My guess is that
omission should have prevented the new GitHub Enterprise functionality
from working, but strangely when I end to end tested it manually with
a real pull request on a test repo it seemed to work ok.  Either way
this commit adds the input var to `action.yml` as it should be.
[1]: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
> Specify GitHub Enterprise input var in action.yml

- README.md
- action.yml
- internal/github/action.go
- label_checker_test.go
Allow the label checker to not fail the build, even when a label
check succeeds, and then use an [`if` condition][1] in a subsequent step
or job to conditionally do something or not. For example: check if a
pull request has a `preview` label and then only deploy an ephemeral
environment if so.
The `allow_failure` mode is set via an input parameter in the
[`with` section][2]: `allow_failure: true`
Closes #276 
[1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
[2]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith
> Add allow failure mode

- .github/workflows/schedule_dockerfile_dependency_updates_issue.yml
The issue generation had been [failing][1] since updating to the `v3`
major version of the [issue bot generator][2].  This commit fixes things
by also using the [separate template action][3] as required from `v3`
onwards.
[1]: https://github.com/agilepathway/label-checker/runs/8282280912?check_suite_focus=true
[2]: https://github.com/imjohnbo/issue-bot/releases/tag/v3.0.0
[3]: https://github.com/imjohnbo/extract-issue-template-fields
> Fix generation of Dockerfile dependencies issues

- .github/workflows/build_and_push_image.yml
- .github/workflows/check-commit-message.yml
- .github/workflows/check_semver_labels.yml
- .github/workflows/dependabot_hack.yml
- .github/workflows/github_tag_and_release.yml
- .github/workflows/integration_test.yml
- .github/workflows/reviewdog.yml
- .github/workflows/schedule_dockerfile_dependency_updates_issue.yml
- .github/workflows/virtual_test.yml
GitHub Actions make the latest [Ubuntu LTS version][1] available every 2
years. They made the [22.04 version available in August 2022], so this
commit updates our GitHub Action workflows to use it.
[1]: https://wiki.ubuntu.com/Releases
[2]: https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/
> Update Ubuntu on GitHub Actions workflows

- .github/workflows/end_to_end_test.yml
This first end-to-end test runs on every pull request, invoking the label checker's `one_of` functionality.  [End-to-end testing][1] gives us greater coverage than the integration tests, as it runs the full label checker. We will add further end-to-end tests later too, to expand the coverage.
[1]: https://circleci.com/blog/what-is-end-to-end-testing/
> Add end-to-end tests

- .github/workflows/end_to_end_test.yml
These really give us great test coverage, and the tests are very simple. They also document the label checker's functionality by example, so overall this is a big win.  If the integration tests ever become difficult or tedious to maintain then we can consider deleting them altogether, as these end-to-end tests may well provide sufficient coverage by themselves.
> Add more end-to-end tests

- .github/workflows/end_to_end_test.yml
This is achieved through an end-to-end test, which gives great test coverage.  It is particularly important that we now have end-to-end tests for the [`allow failure`][1] and [outputs][2] functionality as we [recently broke the label checker][3] by releasing a bug in this area (we had to release another version immediately which reverted the change).
[1]: https://github.com/agilepathway/label-checker#allow-failure-mode
[2]: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
[3]: https://github.com/agilepathway/label-checker/commit/4b2dfdc45359309dc40aaca10c1096a8455112e0
> Test allow failure and outputs functionality

- internal/github/action.go
- label_checker_test.go
As per the [GitHub blog article][1] about this.
Also deleted the integration tests relating to the [allow failure][2]
mode, as the recently added end-to-end tests offer much better test
coverage (the integration tests failed to catch our recent bug there,
whereas the end-to-end tests would have caught it).  So there was no
benefit in refactoring those integration tests as part of this commit,
better to delete them.
[1]: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
[2]: https://github.com/agilepathway/label-checker#allow-failure-mode
> Update deprecated set-output GitHub Action command

- .github/workflows/integration_test.yml
- .github/workflows/virtual_test.yml
- CONTRIBUTING.md
- Dockerfile
- README.md
- go.mod
- go.sum
- internal/github/action.go
- internal/github/action_test.go
- label_checker.go
- scripts/install-mage.sh
[Mage][1] is a Go build tool which we were using to invoke our label checking Go function and to build our Go binary. We don't need Mage though, as we can simply use the standard Go `main` function and build the binary using the standard `go build` command.
It's always good to remove unneeded dependencies, and also Mage was responsible for setting the beginning of the error output (`Error:`) that is displayed on the console.  By removing Mage we now have control of this.  This paves the way for making the error output a [GitHub Actions  workflow command][2] in a future PR, which will mean the error message is highlighted (which will fix #330).
[1]: https://magefile.org/
[2]: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
> Remove dependency on Mage

- .github/workflows/end_to_end_test.yml
- .github/workflows/reviewdog.yml
- README.md
- action.yml
- internal/github/action.go
- internal/github/action_test.go
- internal/github/pullrequest/labels.go
- internal/slice/slice.go
- testdata/github_api.json
- testdata/github_enterprise_server_api.json
This is a new feature that checks for the presence or absence of labels
starting with a given prefix.
This prefix label checking is a powerful feature that allows pull
requests to have scoped labels [in a similar way to GitLab][1].
To use, set the `prefix_mode` as an input parameter in the
`with` section: `prefix_mode: true`.
It is an optional parameter as it defaults to false.
Any string can be used as the prefix.
`one_of`, `any_of`, `none_of` can be used when checking prefixes, but
`all_of` cannot (as `all_of` does not make sense when checking for
labels starting with a given prefix).
Only one prefix can be specified at a time. For instance
`one_of: "type:","visibility/"` is not allowed.
Closes https://github.com/agilepathway/label-checker/issues/328
[1]: …
> Add prefix mode

- .devcontainer/Dockerfile
- .github/workflows/dependabot_hack.yml
To make the application easier to maintain, we will pin just to major versions of [Delve][1] (as minor and patch versions are both always backwards compatible).
[1]: https://github.com/go-delve/delve
> Pin less specific version of the Delve debugger

- .devcontainer/Dockerfile
- .github/workflows/reviewdog.yml
We use [hadolint][1] for Docker linting. To make the application easier
to maintain we will pin just to major versions of [the reviewdog
hadolint GitHub Action][2] (as minor and patch versions are both always
backwards compatible).
* Fix issues reported by hadolint Dockerfile linter
[1]: https://github.com/hadolint/hadolint
[1]: https://github.com/reviewdog/action-hadolint
> Pin less specific version of hadolint

- .devcontainer/Dockerfile
[Using `go get` is deprecated][1].
To use `go install`, we have to separate the package installs into individual lines, but that's no problem.
[1]: https://go.dev/doc/go-get-install-deprecation
Closes #336
> Use `go install` on devcontainer, not `go get`

- .devcontainer/Dockerfile
The benefit of having pinned devcontainer linux dependencies is that it ensures that the devcontainers are idempotent. But in practice not having this is not likely to become a problem. If it ever does, we can pin any troublesome dependencies again (it will be unlikely that we will have to, though).
> Do not pin devcontainer linux dependencies anymore

- Dockerfile
This also involved updating the pinned version of [UPX][1] (which we use to compress the final Docker image size).
[1]: https://www.kali.org/tools/upx-ucl/
> Update Debian version on Dockerfile

- .devcontainer/Dockerfile
- .github/workflows/dependabot_hack.yml
- .github/workflows/reviewdog.yml
To make the application easier to maintain, we will pin just to major versions of [golangci-lint][1] (as minor and patch versions are both always backwards compatible).
[1]: https://golangci-lint.run
> Pin less specific version of golangci-lint

- .devcontainer/Dockerfile
- .github/workflows/dependabot_hack.yml
To make the application easier to maintain, we will pin just to major versions of [gopls][1] (the Go [language server][2]) (as minor and patch versions are both always backwards compatible).
[1]: https://github.com/golang/tools/tree/master/gopls
[2]: https://langserver.org/
> Pin less specific version of gopls

- .github/workflows/dependabot_hack.yml
We were tracking a number of Go dependencies which we have not been installing directly for some time.
> Do not track unused Go devcontainer dependencies

- .devcontainer/Dockerfile
This change should have been in the previous [v1.4.24 release][1], but was accidentally missed.
[1]: https://github.com/agilepathway/label-checker/releases/tag/v1.4.24
> Bump Hoverfly version in devcontainer

- internal/github/action.go
- internal/github/action_test.go
`pull_request_review` event payload does not contain `number` field. However pull request based events (`pull_request`, `pull_request_review` etc) contain `pull_request` object inside payload and inside this object there is `number` field that could be used.
Fixes #385 
Sorry for ugly code, I'm not GO dev. I've run tests and they were passing on my local.
> Use PR number from pull_request object

- .github/workflows/check-commit-message-pr.yml
- .github/workflows/check-commit-message-push.yml
The `@` had been erroneously removed in the `uses` section of our commit message check GitHub Actions.
> Fix commit message checks

- internal/github/action.go
- internal/github/action_test.go
This reverts commit 149b0c22b2b4d7e53f8d7f6c48aa84f543e230f6 ("Use PR number from pull_request object").
Reverting [as this seems to have caused an error in some scenarios][1].
[1]: https://github.com/agilepathway/label-checker/issues/392
> Revert #386

- internal/github/action.go
- internal/github/action_test.go
This reverts commit f7377adc97752df42da96fa1355978c64393934c.
That commit reverted #386 as a precautionary measure, while [investigating a potential bug][1].  It turns out
[that there was no bug][2], though, so this commit reverts that revert.
[1]: https://github.com/agilepathway/label-checker/issues/392
[2]: https://github.com/agilepathway/label-checker/issues/392#issuecomment-1714321629
> Revert "Revert #386 (#393)"

- .github/workflows/build_and_push_image.yml
- .github/workflows/github_tag_and_release.yml
- Dockerfile
Released and checked in my repo
https://hub.docker.com/repository/docker/vanopiano/pull-request-label-checker/tags?page=1&ordering=last_updated
> Add linux arm64 images to the build process

- .github/workflows/github_tag_and_release.yml
A recent change, #405, which added ARM64 Docker images to the build process, introduced a bug (see #419) whereby the new Docker images for each release are no longer being tagged `latest`, as they should be. This commit adds a test to catch this bug, and we will then fix the bug in a subsequent commit.
> Check Docker image is correctly tagged latest

- .github/workflows/github_tag_and_release.yml
The bug was inadvertently introduced by #405, when we migrated to a later version of the [Docker `build-push-action`][1].
[1]: https://github.com/docker/build-push-action
Fixes #419
> Fix bug where Docker image was not tagged latest

- .github/workflows/github_tag_and_release.yml
Our check that (when we make a new release) the Docker image is tagged with latest as well as the new semver version number, which we added in [v1.6.14][1] was broken. This was because we were not pulling the latest tag docker image during the check, so it was not present. Fixed in this commit.
[1]: https://github.com/agilepathway/label-checker/releases/tag/v1.6.14
> Fix latest tag check

- .github/workflows/reviewdog.yml
- .golangci.yml
- internal/github/action.go
- internal/github/action_test.go
- internal/github/pullrequest/labels.go
- internal/slice/slice.go
The fix was to update the major version of golangci-lint.
Also fixed the linting warnings which then appeared.
> Enable golangci-lint checks which were not running

- .github/workflows/github_tag_and_release.yml
The fix is to specify explicitly a goreleaser version of at least 2.
This should not be necessary in theory, but seems to be in
practice.
> Fix goreleaser bug

- .github/workflows/build_and_push_image.yml
- .github/workflows/github_tag_and_release.yml
[Arm][1] deployments have been broken since the previous release to this one, [v.1.62][2]. The breakage wasn't caused by anything in the previous release itself, but rather by the virtualized [QEMU][3] Docker build and push process having developed a fault.  This was always something in danger of happening, as the QEMU virtualized approch is not as stable as a non virtualized approach.  Fortunately [Arm runners are now available for free in GitHub Actions as of January 16, 2025][4]. So this fix simply replaces QEMU with native ARM runners for the Docker build and push on Arm.
Fixes #480
[1]: https://en.wikipedia.org/wiki/ARM_architecture_family
[2]: https://github.com/agilepathway/label-checker/releases/tag/v1.6.62
[3]: https://github.com/docker/setup-qemu-action
[4]: …
> Fix broken ARM deployments

- .github/workflows/github_tag_and_release.yml
The previous release broke amd64 deployments, while adding arm64. Given amd64 is more popular than arm64, this commit reinstates amd64, while unfortunately breaking arm64 again, until we can find a proper fix.
> Fix amd64 deployments (but break arm64)
